// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PTN.InventoryTracking.Persistence.Contexts;

#nullable disable

namespace PTN.InventoryTracking.Persistence.Migrations
{
    [DbContext(typeof(InventoryTrackingDbContext))]
    [Migration("20260429080101_AddAuthenticationAndAuthorization")]
    partial class AddAuthenticationAndAuthorization
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PTN.InventoryTracking.Domain.Entities.AppPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_app_permissions");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_app_permissions_code");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_app_permissions_name");

                    b.ToTable("app_permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f6844f62-5b8f-415a-6297-e885cdc667da"),
                            Code = "products.read",
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Read product and stock summary endpoints",
                            IsActive = true,
                            Name = "Products Read"
                        },
                        new
                        {
                            Id = new Guid("febe00cf-cd8d-f7f0-fbae-9f9b2015c29c"),
                            Code = "products.create",
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Create product records",
                            IsActive = true,
                            Name = "Products Create"
                        },
                        new
                        {
                            Id = new Guid("056d3dde-7c9b-4f80-2bef-448ec032cc47"),
                            Code = "products.update",
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Update product records",
                            IsActive = true,
                            Name = "Products Update"
                        },
                        new
                        {
                            Id = new Guid("5c1bfe4d-52d9-909c-3527-9b921ecaf1f0"),
                            Code = "products.delete",
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Delete product records",
                            IsActive = true,
                            Name = "Products Delete"
                        },
                        new
                        {
                            Id = new Guid("627e24d4-7e9b-df99-ff41-417c379f2e7f"),
                            Code = "warehouses.read",
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Read warehouse records",
                            IsActive = true,
                            Name = "Warehouses Read"
                        },
                        new
                        {
                            Id = new Guid("bb167ee6-8c7a-e6b8-7e81-c06fc2e8fb62"),
                            Code = "warehouses.create",
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Create warehouse records",
                            IsActive = true,
                            Name = "Warehouses Create"
                        },
                        new
                        {
                            Id = new Guid("b0dd0060-ecc3-d5f9-85ff-dfa878fa3b7c"),
                            Code = "warehouses.update",
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Update warehouse records",
                            IsActive = true,
                            Name = "Warehouses Update"
                        },
                        new
                        {
                            Id = new Guid("06c66756-de69-c309-5904-1e03f5cb802f"),
                            Code = "warehouses.delete",
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Delete warehouse records",
                            IsActive = true,
                            Name = "Warehouses Delete"
                        },
                        new
                        {
                            Id = new Guid("6d123192-989d-d078-c886-2afe2dac17d9"),
                            Code = "vehicles.read",
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Read vehicle and vehicle inventory endpoints",
                            IsActive = true,
                            Name = "Vehicles Read"
                        },
                        new
                        {
                            Id = new Guid("5d3e17a6-ee56-63d8-cf19-69f31904c9e5"),
                            Code = "vehicles.create",
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Create vehicle records",
                            IsActive = true,
                            Name = "Vehicles Create"
                        },
                        new
                        {
                            Id = new Guid("e1d455fb-78d0-80ff-11e2-939128d9dfe8"),
                            Code = "vehicles.update",
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Update vehicle records",
                            IsActive = true,
                            Name = "Vehicles Update"
                        },
                        new
                        {
                            Id = new Guid("44cbfd49-9071-bbe9-cbe1-b40f9915db7f"),
                            Code = "vehicles.delete",
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Delete vehicle records",
                            IsActive = true,
                            Name = "Vehicles Delete"
                        },
                        new
                        {
                            Id = new Guid("826a169d-c216-c921-de5c-537103eb0ac8"),
                            Code = "tasks.read",
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Read task, task vehicle and task inventory endpoints",
                            IsActive = true,
                            Name = "Tasks Read"
                        },
                        new
                        {
                            Id = new Guid("f83c6850-a850-3ba5-81d9-a8a04bcd18d2"),
                            Code = "tasks.create",
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Create task records",
                            IsActive = true,
                            Name = "Tasks Create"
                        },
                        new
                        {
                            Id = new Guid("5340d184-3527-50e2-a178-7ccc44e9fb4c"),
                            Code = "tasks.update",
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Update task records",
                            IsActive = true,
                            Name = "Tasks Update"
                        },
                        new
                        {
                            Id = new Guid("709622e0-c98c-a0e1-3d14-cd8a7df9140f"),
                            Code = "tasks.delete",
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Delete task records",
                            IsActive = true,
                            Name = "Tasks Delete"
                        },
                        new
                        {
                            Id = new Guid("fbbb5c2d-039a-8762-baab-4bd664154506"),
                            Code = "inventory-transactions.read",
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Read inventory transaction history",
                            IsActive = true,
                            Name = "Inventory Transactions Read"
                        },
                        new
                        {
                            Id = new Guid("1905b4b2-0ee4-c765-90be-7d0f61c1a31e"),
                            Code = "stock-transfers.create",
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Perform stock transfer operations",
                            IsActive = true,
                            Name = "Stock Transfers Create"
                        });
                });

            modelBuilder.Entity("PTN.InventoryTracking.Domain.Entities.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_app_roles");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_app_roles_code");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_app_roles_name");

                    b.ToTable("app_roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10101010-1010-1010-1010-101010101011"),
                            Code = "ROLE-ADMIN",
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Full access role",
                            IsActive = true,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("10101010-1010-1010-1010-101010101012"),
                            Code = "ROLE-WAREHOUSE-OPERATOR",
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Warehouse and stock transfer operator role",
                            IsActive = true,
                            Name = "WarehouseOperator"
                        },
                        new
                        {
                            Id = new Guid("10101010-1010-1010-1010-101010101013"),
                            Code = "ROLE-TASK-MANAGER",
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Task and vehicle management role",
                            IsActive = true,
                            Name = "TaskManager"
                        });
                });

            modelBuilder.Entity("PTN.InventoryTracking.Domain.Entities.AppRolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_app_role_permissions");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_app_role_permissions_permission_id");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique()
                        .HasDatabaseName("ix_app_role_permissions_role_id_permission_id");

                    b.ToTable("app_role_permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ede9ec13-5fd3-ba9c-a904-17008a9e6365"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("f6844f62-5b8f-415a-6297-e885cdc667da"),
                            RoleId = new Guid("10101010-1010-1010-1010-101010101011")
                        },
                        new
                        {
                            Id = new Guid("108823c6-69c6-0454-60bf-5a859d8892fe"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("febe00cf-cd8d-f7f0-fbae-9f9b2015c29c"),
                            RoleId = new Guid("10101010-1010-1010-1010-101010101011")
                        },
                        new
                        {
                            Id = new Guid("8a3526a3-6db6-4456-c946-842b155809be"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("056d3dde-7c9b-4f80-2bef-448ec032cc47"),
                            RoleId = new Guid("10101010-1010-1010-1010-101010101011")
                        },
                        new
                        {
                            Id = new Guid("069a136f-33c5-34c2-25e0-7a8239d2292a"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("5c1bfe4d-52d9-909c-3527-9b921ecaf1f0"),
                            RoleId = new Guid("10101010-1010-1010-1010-101010101011")
                        },
                        new
                        {
                            Id = new Guid("d4d16e85-3add-013f-779d-92d013126ac2"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("627e24d4-7e9b-df99-ff41-417c379f2e7f"),
                            RoleId = new Guid("10101010-1010-1010-1010-101010101011")
                        },
                        new
                        {
                            Id = new Guid("d40c3516-48a4-8ee2-8ebf-4721e03fce31"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("bb167ee6-8c7a-e6b8-7e81-c06fc2e8fb62"),
                            RoleId = new Guid("10101010-1010-1010-1010-101010101011")
                        },
                        new
                        {
                            Id = new Guid("a6d08d84-b0bf-856f-8c01-1a3be9adcd32"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("b0dd0060-ecc3-d5f9-85ff-dfa878fa3b7c"),
                            RoleId = new Guid("10101010-1010-1010-1010-101010101011")
                        },
                        new
                        {
                            Id = new Guid("f87bd99a-679f-a322-f404-215a90408228"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("06c66756-de69-c309-5904-1e03f5cb802f"),
                            RoleId = new Guid("10101010-1010-1010-1010-101010101011")
                        },
                        new
                        {
                            Id = new Guid("08460690-6de7-7b35-6f89-88be26257faa"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("6d123192-989d-d078-c886-2afe2dac17d9"),
                            RoleId = new Guid("10101010-1010-1010-1010-101010101011")
                        },
                        new
                        {
                            Id = new Guid("db060b28-0443-d45e-01a7-88e00449689f"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("5d3e17a6-ee56-63d8-cf19-69f31904c9e5"),
                            RoleId = new Guid("10101010-1010-1010-1010-101010101011")
                        },
                        new
                        {
                            Id = new Guid("44baeb4e-5729-cad9-a343-73886c0bcc17"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("e1d455fb-78d0-80ff-11e2-939128d9dfe8"),
                            RoleId = new Guid("10101010-1010-1010-1010-101010101011")
                        },
                        new
                        {
                            Id = new Guid("c9a9e48a-0cba-c624-2c3c-9323421939c2"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("44cbfd49-9071-bbe9-cbe1-b40f9915db7f"),
                            RoleId = new Guid("10101010-1010-1010-1010-101010101011")
                        },
                        new
                        {
                            Id = new Guid("cd2f5c7d-ae8c-4361-2d1e-ee682fd1b11d"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("826a169d-c216-c921-de5c-537103eb0ac8"),
                            RoleId = new Guid("10101010-1010-1010-1010-101010101011")
                        },
                        new
                        {
                            Id = new Guid("7ad826b8-66c1-defc-eef7-a8e04335b91b"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("f83c6850-a850-3ba5-81d9-a8a04bcd18d2"),
                            RoleId = new Guid("10101010-1010-1010-1010-101010101011")
                        },
                        new
                        {
                            Id = new Guid("e128286c-298e-b23d-9438-2aa4816b3951"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("5340d184-3527-50e2-a178-7ccc44e9fb4c"),
                            RoleId = new Guid("10101010-1010-1010-1010-101010101011")
                        },
                        new
                        {
                            Id = new Guid("2eb1c131-dd8d-13d6-20c0-e53505695f48"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("709622e0-c98c-a0e1-3d14-cd8a7df9140f"),
                            RoleId = new Guid("10101010-1010-1010-1010-101010101011")
                        },
                        new
                        {
                            Id = new Guid("bf18a65c-871b-6044-0a4e-30016137ef93"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("fbbb5c2d-039a-8762-baab-4bd664154506"),
                            RoleId = new Guid("10101010-1010-1010-1010-101010101011")
                        },
                        new
                        {
                            Id = new Guid("f361505c-eac2-247a-5fae-61ce7079ca9e"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("1905b4b2-0ee4-c765-90be-7d0f61c1a31e"),
                            RoleId = new Guid("10101010-1010-1010-1010-101010101011")
                        },
                        new
                        {
                            Id = new Guid("3531b09c-614a-5439-c96c-2049fac385e2"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("f6844f62-5b8f-415a-6297-e885cdc667da"),
                            RoleId = new Guid("10101010-1010-1010-1010-101010101012")
                        },
                        new
                        {
                            Id = new Guid("127ae5a4-49f8-ce16-c6e5-f82c84ff067c"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("627e24d4-7e9b-df99-ff41-417c379f2e7f"),
                            RoleId = new Guid("10101010-1010-1010-1010-101010101012")
                        },
                        new
                        {
                            Id = new Guid("6c982b3f-1881-855d-4a10-0bdb9012b155"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("b0dd0060-ecc3-d5f9-85ff-dfa878fa3b7c"),
                            RoleId = new Guid("10101010-1010-1010-1010-101010101012")
                        },
                        new
                        {
                            Id = new Guid("938ce833-fe87-c5b6-435a-7db155ac5aba"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("6d123192-989d-d078-c886-2afe2dac17d9"),
                            RoleId = new Guid("10101010-1010-1010-1010-101010101012")
                        },
                        new
                        {
                            Id = new Guid("56677704-ae28-4b27-b468-8cb0a98c2da5"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("826a169d-c216-c921-de5c-537103eb0ac8"),
                            RoleId = new Guid("10101010-1010-1010-1010-101010101012")
                        },
                        new
                        {
                            Id = new Guid("195ad4ea-d0c1-0c05-c4f4-4390335ebfc1"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("fbbb5c2d-039a-8762-baab-4bd664154506"),
                            RoleId = new Guid("10101010-1010-1010-1010-101010101012")
                        },
                        new
                        {
                            Id = new Guid("93a24b5a-0322-c6dd-74ee-aec1b6408b73"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("1905b4b2-0ee4-c765-90be-7d0f61c1a31e"),
                            RoleId = new Guid("10101010-1010-1010-1010-101010101012")
                        },
                        new
                        {
                            Id = new Guid("4dc22b53-7691-e86e-b9cf-54e8bf9a5e70"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("f6844f62-5b8f-415a-6297-e885cdc667da"),
                            RoleId = new Guid("10101010-1010-1010-1010-101010101013")
                        },
                        new
                        {
                            Id = new Guid("7da1ba1e-f1d6-d931-1a45-a5786eb41944"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("6d123192-989d-d078-c886-2afe2dac17d9"),
                            RoleId = new Guid("10101010-1010-1010-1010-101010101013")
                        },
                        new
                        {
                            Id = new Guid("2cf3ee7f-8b2c-c17d-b087-3c6d7af72af6"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("e1d455fb-78d0-80ff-11e2-939128d9dfe8"),
                            RoleId = new Guid("10101010-1010-1010-1010-101010101013")
                        },
                        new
                        {
                            Id = new Guid("7d463a9d-e7c8-ae0a-6216-1ae08b39add8"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("826a169d-c216-c921-de5c-537103eb0ac8"),
                            RoleId = new Guid("10101010-1010-1010-1010-101010101013")
                        },
                        new
                        {
                            Id = new Guid("f1f901e0-6410-2cdf-f884-458adead476d"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("f83c6850-a850-3ba5-81d9-a8a04bcd18d2"),
                            RoleId = new Guid("10101010-1010-1010-1010-101010101013")
                        },
                        new
                        {
                            Id = new Guid("c18534c7-a8a8-105d-e513-48609fcc4114"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("5340d184-3527-50e2-a178-7ccc44e9fb4c"),
                            RoleId = new Guid("10101010-1010-1010-1010-101010101013")
                        },
                        new
                        {
                            Id = new Guid("301988b3-0ca8-8cfb-57de-641928ef4f24"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("fbbb5c2d-039a-8762-baab-4bd664154506"),
                            RoleId = new Guid("10101010-1010-1010-1010-101010101013")
                        });
                });

            modelBuilder.Entity("PTN.InventoryTracking.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_app_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_app_users_email");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasDatabaseName("ix_app_users_user_name");

                    b.ToTable("app_users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("20202020-2020-2020-2020-202020202021"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@ptn.local",
                            FullName = "System Administrator",
                            IsActive = true,
                            PasswordHash = "pbkdf2$100000$adQyMFF/MEDyqS1mZ08ATA==$L4rcPrvAUy/+bShxsmO+6YvNZ4t+5hOBVnjdoROjk68=",
                            UserName = "admin"
                        },
                        new
                        {
                            Id = new Guid("20202020-2020-2020-2020-202020202022"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            Email = "warehouse@ptn.local",
                            FullName = "Warehouse Operator",
                            IsActive = true,
                            PasswordHash = "pbkdf2$100000$fmXCFcONlxHDNILtMYT/tg==$l5v3quqi3kNjhqqcLC7jNEBW2RW0LNmHxwY2xAgI7Gs=",
                            UserName = "warehouse.operator"
                        },
                        new
                        {
                            Id = new Guid("20202020-2020-2020-2020-202020202023"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            Email = "taskmanager@ptn.local",
                            FullName = "Task Manager",
                            IsActive = true,
                            PasswordHash = "pbkdf2$100000$mNGvVDSa8GdorMSan+8s/A==$Ht44IbT0Q6iij1kUu47u+DZ3IKTJTTCJdhk/n7fiZro=",
                            UserName = "task.manager"
                        });
                });

            modelBuilder.Entity("PTN.InventoryTracking.Domain.Entities.AppUserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_app_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_app_user_roles_role_id");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique()
                        .HasDatabaseName("ix_app_user_roles_user_id_role_id");

                    b.ToTable("app_user_roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("474a135a-6bcc-9198-89b6-ffdd370c199f"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            RoleId = new Guid("10101010-1010-1010-1010-101010101011"),
                            UserId = new Guid("20202020-2020-2020-2020-202020202021")
                        },
                        new
                        {
                            Id = new Guid("83cf1153-daf6-ab65-9e0e-9b2542cdfce9"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            RoleId = new Guid("10101010-1010-1010-1010-101010101012"),
                            UserId = new Guid("20202020-2020-2020-2020-202020202022")
                        },
                        new
                        {
                            Id = new Guid("99ec6872-8ad3-50d3-06b3-90356645b868"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            RoleId = new Guid("10101010-1010-1010-1010-101010101013"),
                            UserId = new Guid("20202020-2020-2020-2020-202020202023")
                        });
                });

            modelBuilder.Entity("PTN.InventoryTracking.Domain.Entities.InventoryTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("region");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_tasks");

                    b.HasIndex("Status", "StartDate")
                        .HasDatabaseName("ix_tasks_status_start_date");

                    b.ToTable("tasks", null, t =>
                        {
                            t.HasCheckConstraint("ck_tasks_date_range", "\"end_date\" IS NULL OR \"end_date\" >= \"start_date\"");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444441"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Izmir bolgesindeki aktif saha ekiplerine ekipman destegi",
                            Name = "Izmir Saha Destek Gorevi",
                            Region = "Izmir",
                            StartDate = new DateOnly(2026, 4, 28),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444442"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Enerji kesintisi yasayan noktalar icin mobil jeneratör destegi",
                            EndDate = new DateOnly(2026, 4, 23),
                            Name = "Ankara Acil Enerji Destegi",
                            Region = "Ankara",
                            StartDate = new DateOnly(2026, 4, 20),
                            Status = 3
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444443"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Planlanan saha operasyonu icin hazirlik kaydi",
                            Name = "Bursa Hazirlik Gorevi",
                            Region = "Bursa",
                            StartDate = new DateOnly(2026, 5, 2),
                            Status = 1
                        });
                });

            modelBuilder.Entity("PTN.InventoryTracking.Domain.Entities.InventoryTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("DestinationStockLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("destination_stock_location_id");

                    b.Property<DateTime>("PerformedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("performed_at_utc");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("ReferenceNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reference_note");

                    b.Property<Guid?>("SourceStockLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_stock_location_id");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<int>("TransactionType")
                        .HasColumnType("integer")
                        .HasColumnName("transaction_type");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_inventory_transactions");

                    b.HasIndex("DestinationStockLocationId")
                        .HasDatabaseName("ix_inventory_transactions_destination_stock_location_id");

                    b.HasIndex("PerformedAtUtc")
                        .HasDatabaseName("ix_inventory_transactions_performed_at_utc");

                    b.HasIndex("SourceStockLocationId")
                        .HasDatabaseName("ix_inventory_transactions_source_stock_location_id");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("ix_inventory_transactions_task_id");

                    b.HasIndex("ProductId", "PerformedAtUtc")
                        .HasDatabaseName("ix_inventory_transactions_product_id_performed_at_utc");

                    b.ToTable("inventory_transactions", null, t =>
                        {
                            t.HasCheckConstraint("ck_inventory_transactions_endpoint_presence", "\"source_stock_location_id\" IS NOT NULL OR \"destination_stock_location_id\" IS NOT NULL");

                            t.HasCheckConstraint("ck_inventory_transactions_quantity_positive", "\"quantity\" > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888881"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            DestinationStockLocationId = new Guid("66666666-6666-6666-6666-666666666661"),
                            PerformedAtUtc = new DateTime(2026, 4, 27, 9, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Quantity = 20,
                            ReferenceNote = "Telsiz ilk depo girisi",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888882"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            DestinationStockLocationId = new Guid("66666666-6666-6666-6666-666666666663"),
                            PerformedAtUtc = new DateTime(2026, 4, 28, 8, 15, 0, 0, DateTimeKind.Utc),
                            ProductId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Quantity = 5,
                            ReferenceNote = "Izmir gorevi icin araca yukleme",
                            SourceStockLocationId = new Guid("66666666-6666-6666-6666-666666666661"),
                            TaskId = new Guid("44444444-4444-4444-4444-444444444441"),
                            TransactionType = 2
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888883"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            DestinationStockLocationId = new Guid("66666666-6666-6666-6666-666666666664"),
                            PerformedAtUtc = new DateTime(2026, 4, 28, 8, 45, 0, 0, DateTimeKind.Utc),
                            ProductId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Quantity = 5,
                            ReferenceNote = "Izmir gorevi icin ikinci arac yuklemesi",
                            SourceStockLocationId = new Guid("66666666-6666-6666-6666-666666666661"),
                            TaskId = new Guid("44444444-4444-4444-4444-444444444441"),
                            TransactionType = 2
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888884"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            DestinationStockLocationId = new Guid("66666666-6666-6666-6666-666666666662"),
                            PerformedAtUtc = new DateTime(2026, 4, 19, 14, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = new Guid("11111111-1111-1111-1111-111111111112"),
                            Quantity = 3,
                            ReferenceNote = "Jenerator depo girisi",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888885"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            DestinationStockLocationId = new Guid("66666666-6666-6666-6666-666666666663"),
                            PerformedAtUtc = new DateTime(2026, 4, 28, 9, 5, 0, 0, DateTimeKind.Utc),
                            ProductId = new Guid("11111111-1111-1111-1111-111111111112"),
                            Quantity = 1,
                            ReferenceNote = "Izmir gorevi icin jenerator transferi",
                            SourceStockLocationId = new Guid("66666666-6666-6666-6666-666666666662"),
                            TaskId = new Guid("44444444-4444-4444-4444-444444444441"),
                            TransactionType = 2
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888886"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            DestinationStockLocationId = new Guid("66666666-6666-6666-6666-666666666661"),
                            PerformedAtUtc = new DateTime(2026, 4, 18, 11, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = new Guid("11111111-1111-1111-1111-111111111113"),
                            Quantity = 16,
                            ReferenceNote = "El feneri depo girisi",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888887"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            DestinationStockLocationId = new Guid("66666666-6666-6666-6666-666666666665"),
                            PerformedAtUtc = new DateTime(2026, 4, 20, 7, 5, 0, 0, DateTimeKind.Utc),
                            ProductId = new Guid("11111111-1111-1111-1111-111111111113"),
                            Quantity = 4,
                            ReferenceNote = "Ankara gorevi icin el feneri sevkiyati",
                            SourceStockLocationId = new Guid("66666666-6666-6666-6666-666666666661"),
                            TaskId = new Guid("44444444-4444-4444-4444-444444444442"),
                            TransactionType = 2
                        });
                });

            modelBuilder.Entity("PTN.InventoryTracking.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("unit");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_products_code");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_products_name");

                    b.ToTable("products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Code = "PRD-RADIO-001",
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Saha ekipleri icin el telsizi",
                            IsActive = true,
                            Name = "Telsiz",
                            Unit = "adet"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111112"),
                            Code = "PRD-GEN-001",
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Mobil enerji destegi icin jeneratör",
                            IsActive = true,
                            Name = "Jenerator",
                            Unit = "adet"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111113"),
                            Code = "PRD-FLS-001",
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Acil durum aydinlatma ekipmani",
                            IsActive = true,
                            Name = "El Feneri",
                            Unit = "adet"
                        });
                });

            modelBuilder.Entity("PTN.InventoryTracking.Domain.Entities.StockBalance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid>("StockLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("stock_location_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_stock_balances");

                    b.HasIndex("StockLocationId")
                        .HasDatabaseName("ix_stock_balances_stock_location_id");

                    b.HasIndex("ProductId", "StockLocationId")
                        .IsUnique()
                        .HasDatabaseName("ix_stock_balances_product_id_stock_location_id");

                    b.ToTable("stock_balances", null, t =>
                        {
                            t.HasCheckConstraint("ck_stock_balances_quantity_non_negative", "\"quantity\" >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777771"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Quantity = 10,
                            StockLocationId = new Guid("66666666-6666-6666-6666-666666666661")
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777772"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Quantity = 5,
                            StockLocationId = new Guid("66666666-6666-6666-6666-666666666663")
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777773"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Quantity = 5,
                            StockLocationId = new Guid("66666666-6666-6666-6666-666666666664")
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777774"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = new Guid("11111111-1111-1111-1111-111111111112"),
                            Quantity = 2,
                            StockLocationId = new Guid("66666666-6666-6666-6666-666666666662")
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777775"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = new Guid("11111111-1111-1111-1111-111111111112"),
                            Quantity = 1,
                            StockLocationId = new Guid("66666666-6666-6666-6666-666666666663")
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777776"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = new Guid("11111111-1111-1111-1111-111111111113"),
                            Quantity = 12,
                            StockLocationId = new Guid("66666666-6666-6666-6666-666666666661")
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = new Guid("11111111-1111-1111-1111-111111111113"),
                            Quantity = 4,
                            StockLocationId = new Guid("66666666-6666-6666-6666-666666666665")
                        });
                });

            modelBuilder.Entity("PTN.InventoryTracking.Domain.Entities.StockLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("LocationType")
                        .HasColumnType("integer")
                        .HasColumnName("location_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.Property<Guid?>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("pk_stock_locations");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_stock_locations_name");

                    b.HasIndex("VehicleId")
                        .IsUnique()
                        .HasDatabaseName("ix_stock_locations_vehicle_id");

                    b.HasIndex("WarehouseId")
                        .IsUnique()
                        .HasDatabaseName("ix_stock_locations_warehouse_id");

                    b.ToTable("stock_locations", null, t =>
                        {
                            t.HasCheckConstraint("ck_stock_locations_owner", "(\n    \"location_type\" = 1\n    AND \"warehouse_id\" IS NOT NULL\n    AND \"vehicle_id\" IS NULL\n)\nOR\n(\n    \"location_type\" = 2\n    AND \"vehicle_id\" IS NOT NULL\n    AND \"warehouse_id\" IS NULL\n)");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666661"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LocationType = 1,
                            Name = "Ana Depo Stok Lokasyonu",
                            WarehouseId = new Guid("22222222-2222-2222-2222-222222222221")
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666662"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LocationType = 1,
                            Name = "Ankara Destek Deposu Stok Lokasyonu",
                            WarehouseId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666663"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LocationType = 2,
                            Name = "34 ABC 123 Arac Lokasyonu",
                            VehicleId = new Guid("33333333-3333-3333-3333-333333333331")
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666664"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LocationType = 2,
                            Name = "06 XYZ 789 Arac Lokasyonu",
                            VehicleId = new Guid("33333333-3333-3333-3333-333333333332")
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666665"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LocationType = 2,
                            Name = "26 ES 001 Arac Lokasyonu",
                            VehicleId = new Guid("33333333-3333-3333-3333-333333333333")
                        });
                });

            modelBuilder.Entity("PTN.InventoryTracking.Domain.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("license_plate");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("vehicle_type");

                    b.HasKey("Id")
                        .HasName("pk_vehicles");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_vehicles_code");

                    b.HasIndex("LicensePlate")
                        .IsUnique()
                        .HasDatabaseName("ix_vehicles_license_plate");

                    b.ToTable("vehicles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333331"),
                            Code = "VEH-001",
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LicensePlate = "34 ABC 123",
                            VehicleType = "Panelvan"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333332"),
                            Code = "VEH-002",
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LicensePlate = "06 XYZ 789",
                            VehicleType = "Kamyonet"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Code = "VEH-003",
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LicensePlate = "26 ES 001",
                            VehicleType = "SUV"
                        });
                });

            modelBuilder.Entity("PTN.InventoryTracking.Domain.Entities.VehicleTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at_utc");

                    b.Property<string>("AssignmentNote")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("assignment_note");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("ReleasedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("released_at_utc");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id")
                        .HasName("pk_vehicle_tasks");

                    b.HasIndex("TaskId", "AssignedAtUtc")
                        .HasDatabaseName("ix_vehicle_tasks_task_id_assigned_at_utc");

                    b.HasIndex("VehicleId", "AssignedAtUtc")
                        .HasDatabaseName("ix_vehicle_tasks_vehicle_id_assigned_at_utc");

                    b.ToTable("vehicle_tasks", null, t =>
                        {
                            t.HasCheckConstraint("ck_vehicle_tasks_release_after_assign", "\"released_at_utc\" IS NULL OR \"released_at_utc\" >= \"assigned_at_utc\"");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555551"),
                            AssignedAtUtc = new DateTime(2026, 4, 28, 7, 30, 0, 0, DateTimeKind.Utc),
                            AssignmentNote = "Izmir gorevi icin ilk arac atamasi",
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            TaskId = new Guid("44444444-4444-4444-4444-444444444441"),
                            VehicleId = new Guid("33333333-3333-3333-3333-333333333331")
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555552"),
                            AssignedAtUtc = new DateTime(2026, 4, 28, 8, 0, 0, 0, DateTimeKind.Utc),
                            AssignmentNote = "Telsiz destegi icin ikinci arac",
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            TaskId = new Guid("44444444-4444-4444-4444-444444444441"),
                            VehicleId = new Guid("33333333-3333-3333-3333-333333333332")
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555553"),
                            AssignedAtUtc = new DateTime(2026, 4, 20, 6, 45, 0, 0, DateTimeKind.Utc),
                            AssignmentNote = "Tamamlanan enerji gorevi kaydi",
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            ReleasedAtUtc = new DateTime(2026, 4, 23, 18, 15, 0, 0, DateTimeKind.Utc),
                            TaskId = new Guid("44444444-4444-4444-4444-444444444442"),
                            VehicleId = new Guid("33333333-3333-3333-3333-333333333333")
                        });
                });

            modelBuilder.Entity("PTN.InventoryTracking.Domain.Entities.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("address");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("region");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_warehouses");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_warehouses_code");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_warehouses_name");

                    b.ToTable("warehouses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222221"),
                            Address = "Eskisehir Merkez Operasyon Kampusu",
                            Code = "WH-ESK-001",
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Ana Depo",
                            Region = "Eskisehir"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Address = "Ankara Sincan Lojistik Alani",
                            Code = "WH-ANK-001",
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Ankara Destek Deposu",
                            Region = "Ankara"
                        });
                });

            modelBuilder.Entity("PTN.InventoryTracking.Domain.Entities.AppRolePermission", b =>
                {
                    b.HasOne("PTN.InventoryTracking.Domain.Entities.AppPermission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_app_role_permissions_app_permissions_permission_id");

                    b.HasOne("PTN.InventoryTracking.Domain.Entities.AppRole", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_app_role_permissions_app_roles_role_id");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PTN.InventoryTracking.Domain.Entities.AppUserRole", b =>
                {
                    b.HasOne("PTN.InventoryTracking.Domain.Entities.AppRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_app_user_roles_app_roles_role_id");

                    b.HasOne("PTN.InventoryTracking.Domain.Entities.AppUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_app_user_roles_app_users_user_id");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PTN.InventoryTracking.Domain.Entities.InventoryTransaction", b =>
                {
                    b.HasOne("PTN.InventoryTracking.Domain.Entities.StockLocation", "DestinationStockLocation")
                        .WithMany("DestinationTransactions")
                        .HasForeignKey("DestinationStockLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_inventory_transactions_stock_locations_destination_stock_lo");

                    b.HasOne("PTN.InventoryTracking.Domain.Entities.Product", "Product")
                        .WithMany("InventoryTransactions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_transactions_products_product_id");

                    b.HasOne("PTN.InventoryTracking.Domain.Entities.StockLocation", "SourceStockLocation")
                        .WithMany("SourceTransactions")
                        .HasForeignKey("SourceStockLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_inventory_transactions_stock_locations_source_stock_locatio");

                    b.HasOne("PTN.InventoryTracking.Domain.Entities.InventoryTask", "Task")
                        .WithMany("InventoryTransactions")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_inventory_transactions_tasks_task_id");

                    b.Navigation("DestinationStockLocation");

                    b.Navigation("Product");

                    b.Navigation("SourceStockLocation");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("PTN.InventoryTracking.Domain.Entities.StockBalance", b =>
                {
                    b.HasOne("PTN.InventoryTracking.Domain.Entities.Product", "Product")
                        .WithMany("StockBalances")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stock_balances_products_product_id");

                    b.HasOne("PTN.InventoryTracking.Domain.Entities.StockLocation", "StockLocation")
                        .WithMany("StockBalances")
                        .HasForeignKey("StockLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stock_balances_stock_locations_stock_location_id");

                    b.Navigation("Product");

                    b.Navigation("StockLocation");
                });

            modelBuilder.Entity("PTN.InventoryTracking.Domain.Entities.StockLocation", b =>
                {
                    b.HasOne("PTN.InventoryTracking.Domain.Entities.Vehicle", "Vehicle")
                        .WithOne("StockLocation")
                        .HasForeignKey("PTN.InventoryTracking.Domain.Entities.StockLocation", "VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_stock_locations_vehicles_vehicle_id");

                    b.HasOne("PTN.InventoryTracking.Domain.Entities.Warehouse", "Warehouse")
                        .WithOne("StockLocation")
                        .HasForeignKey("PTN.InventoryTracking.Domain.Entities.StockLocation", "WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_stock_locations_warehouses_warehouse_id");

                    b.Navigation("Vehicle");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("PTN.InventoryTracking.Domain.Entities.VehicleTask", b =>
                {
                    b.HasOne("PTN.InventoryTracking.Domain.Entities.InventoryTask", "Task")
                        .WithMany("VehicleTasks")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vehicle_tasks_tasks_task_id");

                    b.HasOne("PTN.InventoryTracking.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("VehicleTasks")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vehicle_tasks_vehicles_vehicle_id");

                    b.Navigation("Task");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("PTN.InventoryTracking.Domain.Entities.AppPermission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("PTN.InventoryTracking.Domain.Entities.AppRole", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("PTN.InventoryTracking.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("PTN.InventoryTracking.Domain.Entities.InventoryTask", b =>
                {
                    b.Navigation("InventoryTransactions");

                    b.Navigation("VehicleTasks");
                });

            modelBuilder.Entity("PTN.InventoryTracking.Domain.Entities.Product", b =>
                {
                    b.Navigation("InventoryTransactions");

                    b.Navigation("StockBalances");
                });

            modelBuilder.Entity("PTN.InventoryTracking.Domain.Entities.StockLocation", b =>
                {
                    b.Navigation("DestinationTransactions");

                    b.Navigation("SourceTransactions");

                    b.Navigation("StockBalances");
                });

            modelBuilder.Entity("PTN.InventoryTracking.Domain.Entities.Vehicle", b =>
                {
                    b.Navigation("StockLocation");

                    b.Navigation("VehicleTasks");
                });

            modelBuilder.Entity("PTN.InventoryTracking.Domain.Entities.Warehouse", b =>
                {
                    b.Navigation("StockLocation");
                });
#pragma warning restore 612, 618
        }
    }
}
