// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PTN.InventoryTracking.Persistence.Contexts;

#nullable disable

namespace PTN.InventoryTracking.Persistence.Migrations
{
    [DbContext(typeof(InventoryTrackingDbContext))]
    [Migration("20260429071318_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PTN.InventoryTracking.Domain.Entities.InventoryTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("region");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_tasks");

                    b.HasIndex("Status", "StartDate")
                        .HasDatabaseName("ix_tasks_status_start_date");

                    b.ToTable("tasks", null, t =>
                        {
                            t.HasCheckConstraint("ck_tasks_date_range", "\"end_date\" IS NULL OR \"end_date\" >= \"start_date\"");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444441"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Izmir bolgesindeki aktif saha ekiplerine ekipman destegi",
                            Name = "Izmir Saha Destek Gorevi",
                            Region = "Izmir",
                            StartDate = new DateOnly(2026, 4, 28),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444442"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Enerji kesintisi yasayan noktalar icin mobil jeneratör destegi",
                            EndDate = new DateOnly(2026, 4, 23),
                            Name = "Ankara Acil Enerji Destegi",
                            Region = "Ankara",
                            StartDate = new DateOnly(2026, 4, 20),
                            Status = 3
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444443"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Planlanan saha operasyonu icin hazirlik kaydi",
                            Name = "Bursa Hazirlik Gorevi",
                            Region = "Bursa",
                            StartDate = new DateOnly(2026, 5, 2),
                            Status = 1
                        });
                });

            modelBuilder.Entity("PTN.InventoryTracking.Domain.Entities.InventoryTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("DestinationStockLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("destination_stock_location_id");

                    b.Property<DateTime>("PerformedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("performed_at_utc");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("ReferenceNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reference_note");

                    b.Property<Guid?>("SourceStockLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_stock_location_id");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<int>("TransactionType")
                        .HasColumnType("integer")
                        .HasColumnName("transaction_type");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_inventory_transactions");

                    b.HasIndex("DestinationStockLocationId")
                        .HasDatabaseName("ix_inventory_transactions_destination_stock_location_id");

                    b.HasIndex("PerformedAtUtc")
                        .HasDatabaseName("ix_inventory_transactions_performed_at_utc");

                    b.HasIndex("SourceStockLocationId")
                        .HasDatabaseName("ix_inventory_transactions_source_stock_location_id");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("ix_inventory_transactions_task_id");

                    b.HasIndex("ProductId", "PerformedAtUtc")
                        .HasDatabaseName("ix_inventory_transactions_product_id_performed_at_utc");

                    b.ToTable("inventory_transactions", null, t =>
                        {
                            t.HasCheckConstraint("ck_inventory_transactions_endpoint_presence", "\"source_stock_location_id\" IS NOT NULL OR \"destination_stock_location_id\" IS NOT NULL");

                            t.HasCheckConstraint("ck_inventory_transactions_quantity_positive", "\"quantity\" > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888881"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            DestinationStockLocationId = new Guid("66666666-6666-6666-6666-666666666661"),
                            PerformedAtUtc = new DateTime(2026, 4, 27, 9, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Quantity = 20,
                            ReferenceNote = "Telsiz ilk depo girisi",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888882"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            DestinationStockLocationId = new Guid("66666666-6666-6666-6666-666666666663"),
                            PerformedAtUtc = new DateTime(2026, 4, 28, 8, 15, 0, 0, DateTimeKind.Utc),
                            ProductId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Quantity = 5,
                            ReferenceNote = "Izmir gorevi icin araca yukleme",
                            SourceStockLocationId = new Guid("66666666-6666-6666-6666-666666666661"),
                            TaskId = new Guid("44444444-4444-4444-4444-444444444441"),
                            TransactionType = 2
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888883"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            DestinationStockLocationId = new Guid("66666666-6666-6666-6666-666666666664"),
                            PerformedAtUtc = new DateTime(2026, 4, 28, 8, 45, 0, 0, DateTimeKind.Utc),
                            ProductId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Quantity = 5,
                            ReferenceNote = "Izmir gorevi icin ikinci arac yuklemesi",
                            SourceStockLocationId = new Guid("66666666-6666-6666-6666-666666666661"),
                            TaskId = new Guid("44444444-4444-4444-4444-444444444441"),
                            TransactionType = 2
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888884"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            DestinationStockLocationId = new Guid("66666666-6666-6666-6666-666666666662"),
                            PerformedAtUtc = new DateTime(2026, 4, 19, 14, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = new Guid("11111111-1111-1111-1111-111111111112"),
                            Quantity = 3,
                            ReferenceNote = "Jenerator depo girisi",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888885"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            DestinationStockLocationId = new Guid("66666666-6666-6666-6666-666666666663"),
                            PerformedAtUtc = new DateTime(2026, 4, 28, 9, 5, 0, 0, DateTimeKind.Utc),
                            ProductId = new Guid("11111111-1111-1111-1111-111111111112"),
                            Quantity = 1,
                            ReferenceNote = "Izmir gorevi icin jenerator transferi",
                            SourceStockLocationId = new Guid("66666666-6666-6666-6666-666666666662"),
                            TaskId = new Guid("44444444-4444-4444-4444-444444444441"),
                            TransactionType = 2
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888886"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            DestinationStockLocationId = new Guid("66666666-6666-6666-6666-666666666661"),
                            PerformedAtUtc = new DateTime(2026, 4, 18, 11, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = new Guid("11111111-1111-1111-1111-111111111113"),
                            Quantity = 16,
                            ReferenceNote = "El feneri depo girisi",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888887"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            DestinationStockLocationId = new Guid("66666666-6666-6666-6666-666666666665"),
                            PerformedAtUtc = new DateTime(2026, 4, 20, 7, 5, 0, 0, DateTimeKind.Utc),
                            ProductId = new Guid("11111111-1111-1111-1111-111111111113"),
                            Quantity = 4,
                            ReferenceNote = "Ankara gorevi icin el feneri sevkiyati",
                            SourceStockLocationId = new Guid("66666666-6666-6666-6666-666666666661"),
                            TaskId = new Guid("44444444-4444-4444-4444-444444444442"),
                            TransactionType = 2
                        });
                });

            modelBuilder.Entity("PTN.InventoryTracking.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("unit");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_products_code");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_products_name");

                    b.ToTable("products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Code = "PRD-RADIO-001",
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Saha ekipleri icin el telsizi",
                            IsActive = true,
                            Name = "Telsiz",
                            Unit = "adet"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111112"),
                            Code = "PRD-GEN-001",
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Mobil enerji destegi icin jeneratör",
                            IsActive = true,
                            Name = "Jenerator",
                            Unit = "adet"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111113"),
                            Code = "PRD-FLS-001",
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Acil durum aydinlatma ekipmani",
                            IsActive = true,
                            Name = "El Feneri",
                            Unit = "adet"
                        });
                });

            modelBuilder.Entity("PTN.InventoryTracking.Domain.Entities.StockBalance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid>("StockLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("stock_location_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_stock_balances");

                    b.HasIndex("StockLocationId")
                        .HasDatabaseName("ix_stock_balances_stock_location_id");

                    b.HasIndex("ProductId", "StockLocationId")
                        .IsUnique()
                        .HasDatabaseName("ix_stock_balances_product_id_stock_location_id");

                    b.ToTable("stock_balances", null, t =>
                        {
                            t.HasCheckConstraint("ck_stock_balances_quantity_non_negative", "\"quantity\" >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777771"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Quantity = 10,
                            StockLocationId = new Guid("66666666-6666-6666-6666-666666666661")
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777772"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Quantity = 5,
                            StockLocationId = new Guid("66666666-6666-6666-6666-666666666663")
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777773"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Quantity = 5,
                            StockLocationId = new Guid("66666666-6666-6666-6666-666666666664")
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777774"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = new Guid("11111111-1111-1111-1111-111111111112"),
                            Quantity = 2,
                            StockLocationId = new Guid("66666666-6666-6666-6666-666666666662")
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777775"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = new Guid("11111111-1111-1111-1111-111111111112"),
                            Quantity = 1,
                            StockLocationId = new Guid("66666666-6666-6666-6666-666666666663")
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777776"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = new Guid("11111111-1111-1111-1111-111111111113"),
                            Quantity = 12,
                            StockLocationId = new Guid("66666666-6666-6666-6666-666666666661")
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = new Guid("11111111-1111-1111-1111-111111111113"),
                            Quantity = 4,
                            StockLocationId = new Guid("66666666-6666-6666-6666-666666666665")
                        });
                });

            modelBuilder.Entity("PTN.InventoryTracking.Domain.Entities.StockLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("LocationType")
                        .HasColumnType("integer")
                        .HasColumnName("location_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.Property<Guid?>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("pk_stock_locations");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_stock_locations_name");

                    b.HasIndex("VehicleId")
                        .IsUnique()
                        .HasDatabaseName("ix_stock_locations_vehicle_id");

                    b.HasIndex("WarehouseId")
                        .IsUnique()
                        .HasDatabaseName("ix_stock_locations_warehouse_id");

                    b.ToTable("stock_locations", null, t =>
                        {
                            t.HasCheckConstraint("ck_stock_locations_owner", "(\n    \"location_type\" = 1\n    AND \"warehouse_id\" IS NOT NULL\n    AND \"vehicle_id\" IS NULL\n)\nOR\n(\n    \"location_type\" = 2\n    AND \"vehicle_id\" IS NOT NULL\n    AND \"warehouse_id\" IS NULL\n)");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666661"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LocationType = 1,
                            Name = "Ana Depo Stok Lokasyonu",
                            WarehouseId = new Guid("22222222-2222-2222-2222-222222222221")
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666662"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LocationType = 1,
                            Name = "Ankara Destek Deposu Stok Lokasyonu",
                            WarehouseId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666663"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LocationType = 2,
                            Name = "34 ABC 123 Arac Lokasyonu",
                            VehicleId = new Guid("33333333-3333-3333-3333-333333333331")
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666664"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LocationType = 2,
                            Name = "06 XYZ 789 Arac Lokasyonu",
                            VehicleId = new Guid("33333333-3333-3333-3333-333333333332")
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666665"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LocationType = 2,
                            Name = "26 ES 001 Arac Lokasyonu",
                            VehicleId = new Guid("33333333-3333-3333-3333-333333333333")
                        });
                });

            modelBuilder.Entity("PTN.InventoryTracking.Domain.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("license_plate");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("vehicle_type");

                    b.HasKey("Id")
                        .HasName("pk_vehicles");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_vehicles_code");

                    b.HasIndex("LicensePlate")
                        .IsUnique()
                        .HasDatabaseName("ix_vehicles_license_plate");

                    b.ToTable("vehicles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333331"),
                            Code = "VEH-001",
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LicensePlate = "34 ABC 123",
                            VehicleType = "Panelvan"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333332"),
                            Code = "VEH-002",
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LicensePlate = "06 XYZ 789",
                            VehicleType = "Kamyonet"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Code = "VEH-003",
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LicensePlate = "26 ES 001",
                            VehicleType = "SUV"
                        });
                });

            modelBuilder.Entity("PTN.InventoryTracking.Domain.Entities.VehicleTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at_utc");

                    b.Property<string>("AssignmentNote")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("assignment_note");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("ReleasedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("released_at_utc");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id")
                        .HasName("pk_vehicle_tasks");

                    b.HasIndex("TaskId", "AssignedAtUtc")
                        .HasDatabaseName("ix_vehicle_tasks_task_id_assigned_at_utc");

                    b.HasIndex("VehicleId", "AssignedAtUtc")
                        .HasDatabaseName("ix_vehicle_tasks_vehicle_id_assigned_at_utc");

                    b.ToTable("vehicle_tasks", null, t =>
                        {
                            t.HasCheckConstraint("ck_vehicle_tasks_release_after_assign", "\"released_at_utc\" IS NULL OR \"released_at_utc\" >= \"assigned_at_utc\"");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555551"),
                            AssignedAtUtc = new DateTime(2026, 4, 28, 7, 30, 0, 0, DateTimeKind.Utc),
                            AssignmentNote = "Izmir gorevi icin ilk arac atamasi",
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            TaskId = new Guid("44444444-4444-4444-4444-444444444441"),
                            VehicleId = new Guid("33333333-3333-3333-3333-333333333331")
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555552"),
                            AssignedAtUtc = new DateTime(2026, 4, 28, 8, 0, 0, 0, DateTimeKind.Utc),
                            AssignmentNote = "Telsiz destegi icin ikinci arac",
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            TaskId = new Guid("44444444-4444-4444-4444-444444444441"),
                            VehicleId = new Guid("33333333-3333-3333-3333-333333333332")
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555553"),
                            AssignedAtUtc = new DateTime(2026, 4, 20, 6, 45, 0, 0, DateTimeKind.Utc),
                            AssignmentNote = "Tamamlanan enerji gorevi kaydi",
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            ReleasedAtUtc = new DateTime(2026, 4, 23, 18, 15, 0, 0, DateTimeKind.Utc),
                            TaskId = new Guid("44444444-4444-4444-4444-444444444442"),
                            VehicleId = new Guid("33333333-3333-3333-3333-333333333333")
                        });
                });

            modelBuilder.Entity("PTN.InventoryTracking.Domain.Entities.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("address");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("region");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_warehouses");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_warehouses_code");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_warehouses_name");

                    b.ToTable("warehouses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222221"),
                            Address = "Eskisehir Merkez Operasyon Kampusu",
                            Code = "WH-ESK-001",
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Ana Depo",
                            Region = "Eskisehir"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Address = "Ankara Sincan Lojistik Alani",
                            Code = "WH-ANK-001",
                            CreatedAtUtc = new DateTime(2026, 4, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Ankara Destek Deposu",
                            Region = "Ankara"
                        });
                });

            modelBuilder.Entity("PTN.InventoryTracking.Domain.Entities.InventoryTransaction", b =>
                {
                    b.HasOne("PTN.InventoryTracking.Domain.Entities.StockLocation", "DestinationStockLocation")
                        .WithMany("DestinationTransactions")
                        .HasForeignKey("DestinationStockLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_inventory_transactions_stock_locations_destination_stock_lo");

                    b.HasOne("PTN.InventoryTracking.Domain.Entities.Product", "Product")
                        .WithMany("InventoryTransactions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_transactions_products_product_id");

                    b.HasOne("PTN.InventoryTracking.Domain.Entities.StockLocation", "SourceStockLocation")
                        .WithMany("SourceTransactions")
                        .HasForeignKey("SourceStockLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_inventory_transactions_stock_locations_source_stock_locatio");

                    b.HasOne("PTN.InventoryTracking.Domain.Entities.InventoryTask", "Task")
                        .WithMany("InventoryTransactions")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_inventory_transactions_tasks_task_id");

                    b.Navigation("DestinationStockLocation");

                    b.Navigation("Product");

                    b.Navigation("SourceStockLocation");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("PTN.InventoryTracking.Domain.Entities.StockBalance", b =>
                {
                    b.HasOne("PTN.InventoryTracking.Domain.Entities.Product", "Product")
                        .WithMany("StockBalances")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stock_balances_products_product_id");

                    b.HasOne("PTN.InventoryTracking.Domain.Entities.StockLocation", "StockLocation")
                        .WithMany("StockBalances")
                        .HasForeignKey("StockLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stock_balances_stock_locations_stock_location_id");

                    b.Navigation("Product");

                    b.Navigation("StockLocation");
                });

            modelBuilder.Entity("PTN.InventoryTracking.Domain.Entities.StockLocation", b =>
                {
                    b.HasOne("PTN.InventoryTracking.Domain.Entities.Vehicle", "Vehicle")
                        .WithOne("StockLocation")
                        .HasForeignKey("PTN.InventoryTracking.Domain.Entities.StockLocation", "VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_stock_locations_vehicles_vehicle_id");

                    b.HasOne("PTN.InventoryTracking.Domain.Entities.Warehouse", "Warehouse")
                        .WithOne("StockLocation")
                        .HasForeignKey("PTN.InventoryTracking.Domain.Entities.StockLocation", "WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_stock_locations_warehouses_warehouse_id");

                    b.Navigation("Vehicle");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("PTN.InventoryTracking.Domain.Entities.VehicleTask", b =>
                {
                    b.HasOne("PTN.InventoryTracking.Domain.Entities.InventoryTask", "Task")
                        .WithMany("VehicleTasks")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vehicle_tasks_tasks_task_id");

                    b.HasOne("PTN.InventoryTracking.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("VehicleTasks")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vehicle_tasks_vehicles_vehicle_id");

                    b.Navigation("Task");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("PTN.InventoryTracking.Domain.Entities.InventoryTask", b =>
                {
                    b.Navigation("InventoryTransactions");

                    b.Navigation("VehicleTasks");
                });

            modelBuilder.Entity("PTN.InventoryTracking.Domain.Entities.Product", b =>
                {
                    b.Navigation("InventoryTransactions");

                    b.Navigation("StockBalances");
                });

            modelBuilder.Entity("PTN.InventoryTracking.Domain.Entities.StockLocation", b =>
                {
                    b.Navigation("DestinationTransactions");

                    b.Navigation("SourceTransactions");

                    b.Navigation("StockBalances");
                });

            modelBuilder.Entity("PTN.InventoryTracking.Domain.Entities.Vehicle", b =>
                {
                    b.Navigation("StockLocation");

                    b.Navigation("VehicleTasks");
                });

            modelBuilder.Entity("PTN.InventoryTracking.Domain.Entities.Warehouse", b =>
                {
                    b.Navigation("StockLocation");
                });
#pragma warning restore 612, 618
        }
    }
}
