// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PTN.InventoryTracking.Persistence.Contexts;

#nullable disable

namespace PTN.InventoryTracking.Persistence.Migrations
{
    [DbContext(typeof(InventoryTrackingDbContext))]
    [Migration("20260429070215_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PTN.InventoryTracking.Domain.Entities.InventoryTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("region");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_tasks");

                    b.HasIndex("Status", "StartDate")
                        .HasDatabaseName("ix_tasks_status_start_date");

                    b.ToTable("tasks", null, t =>
                        {
                            t.HasCheckConstraint("ck_tasks_date_range", "\"end_date\" IS NULL OR \"end_date\" >= \"start_date\"");
                        });
                });

            modelBuilder.Entity("PTN.InventoryTracking.Domain.Entities.InventoryTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("DestinationStockLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("destination_stock_location_id");

                    b.Property<DateTime>("PerformedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("performed_at_utc");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("ReferenceNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reference_note");

                    b.Property<Guid?>("SourceStockLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_stock_location_id");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<int>("TransactionType")
                        .HasColumnType("integer")
                        .HasColumnName("transaction_type");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_inventory_transactions");

                    b.HasIndex("DestinationStockLocationId")
                        .HasDatabaseName("ix_inventory_transactions_destination_stock_location_id");

                    b.HasIndex("PerformedAtUtc")
                        .HasDatabaseName("ix_inventory_transactions_performed_at_utc");

                    b.HasIndex("SourceStockLocationId")
                        .HasDatabaseName("ix_inventory_transactions_source_stock_location_id");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("ix_inventory_transactions_task_id");

                    b.HasIndex("ProductId", "PerformedAtUtc")
                        .HasDatabaseName("ix_inventory_transactions_product_id_performed_at_utc");

                    b.ToTable("inventory_transactions", null, t =>
                        {
                            t.HasCheckConstraint("ck_inventory_transactions_endpoint_presence", "\"source_stock_location_id\" IS NOT NULL OR \"destination_stock_location_id\" IS NOT NULL");

                            t.HasCheckConstraint("ck_inventory_transactions_quantity_positive", "\"quantity\" > 0");
                        });
                });

            modelBuilder.Entity("PTN.InventoryTracking.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("unit");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_products_code");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_products_name");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("PTN.InventoryTracking.Domain.Entities.StockBalance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid>("StockLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("stock_location_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_stock_balances");

                    b.HasIndex("StockLocationId")
                        .HasDatabaseName("ix_stock_balances_stock_location_id");

                    b.HasIndex("ProductId", "StockLocationId")
                        .IsUnique()
                        .HasDatabaseName("ix_stock_balances_product_id_stock_location_id");

                    b.ToTable("stock_balances", null, t =>
                        {
                            t.HasCheckConstraint("ck_stock_balances_quantity_non_negative", "\"quantity\" >= 0");
                        });
                });

            modelBuilder.Entity("PTN.InventoryTracking.Domain.Entities.StockLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("LocationType")
                        .HasColumnType("integer")
                        .HasColumnName("location_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.Property<Guid?>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("pk_stock_locations");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_stock_locations_name");

                    b.HasIndex("VehicleId")
                        .IsUnique()
                        .HasDatabaseName("ix_stock_locations_vehicle_id");

                    b.HasIndex("WarehouseId")
                        .IsUnique()
                        .HasDatabaseName("ix_stock_locations_warehouse_id");

                    b.ToTable("stock_locations", null, t =>
                        {
                            t.HasCheckConstraint("ck_stock_locations_owner", "(\n    \"location_type\" = 1\n    AND \"warehouse_id\" IS NOT NULL\n    AND \"vehicle_id\" IS NULL\n)\nOR\n(\n    \"location_type\" = 2\n    AND \"vehicle_id\" IS NOT NULL\n    AND \"warehouse_id\" IS NULL\n)");
                        });
                });

            modelBuilder.Entity("PTN.InventoryTracking.Domain.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("license_plate");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("vehicle_type");

                    b.HasKey("Id")
                        .HasName("pk_vehicles");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_vehicles_code");

                    b.HasIndex("LicensePlate")
                        .IsUnique()
                        .HasDatabaseName("ix_vehicles_license_plate");

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("PTN.InventoryTracking.Domain.Entities.VehicleTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at_utc");

                    b.Property<string>("AssignmentNote")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("assignment_note");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("ReleasedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("released_at_utc");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id")
                        .HasName("pk_vehicle_tasks");

                    b.HasIndex("TaskId", "AssignedAtUtc")
                        .HasDatabaseName("ix_vehicle_tasks_task_id_assigned_at_utc");

                    b.HasIndex("VehicleId", "AssignedAtUtc")
                        .HasDatabaseName("ix_vehicle_tasks_vehicle_id_assigned_at_utc");

                    b.ToTable("vehicle_tasks", null, t =>
                        {
                            t.HasCheckConstraint("ck_vehicle_tasks_release_after_assign", "\"released_at_utc\" IS NULL OR \"released_at_utc\" >= \"assigned_at_utc\"");
                        });
                });

            modelBuilder.Entity("PTN.InventoryTracking.Domain.Entities.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("address");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("region");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_warehouses");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_warehouses_code");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_warehouses_name");

                    b.ToTable("warehouses", (string)null);
                });

            modelBuilder.Entity("PTN.InventoryTracking.Domain.Entities.InventoryTransaction", b =>
                {
                    b.HasOne("PTN.InventoryTracking.Domain.Entities.StockLocation", "DestinationStockLocation")
                        .WithMany("DestinationTransactions")
                        .HasForeignKey("DestinationStockLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_inventory_transactions_stock_locations_destination_stock_lo");

                    b.HasOne("PTN.InventoryTracking.Domain.Entities.Product", "Product")
                        .WithMany("InventoryTransactions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_transactions_products_product_id");

                    b.HasOne("PTN.InventoryTracking.Domain.Entities.StockLocation", "SourceStockLocation")
                        .WithMany("SourceTransactions")
                        .HasForeignKey("SourceStockLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_inventory_transactions_stock_locations_source_stock_locatio");

                    b.HasOne("PTN.InventoryTracking.Domain.Entities.InventoryTask", "Task")
                        .WithMany("InventoryTransactions")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_inventory_transactions_tasks_task_id");

                    b.Navigation("DestinationStockLocation");

                    b.Navigation("Product");

                    b.Navigation("SourceStockLocation");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("PTN.InventoryTracking.Domain.Entities.StockBalance", b =>
                {
                    b.HasOne("PTN.InventoryTracking.Domain.Entities.Product", "Product")
                        .WithMany("StockBalances")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stock_balances_products_product_id");

                    b.HasOne("PTN.InventoryTracking.Domain.Entities.StockLocation", "StockLocation")
                        .WithMany("StockBalances")
                        .HasForeignKey("StockLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stock_balances_stock_locations_stock_location_id");

                    b.Navigation("Product");

                    b.Navigation("StockLocation");
                });

            modelBuilder.Entity("PTN.InventoryTracking.Domain.Entities.StockLocation", b =>
                {
                    b.HasOne("PTN.InventoryTracking.Domain.Entities.Vehicle", "Vehicle")
                        .WithOne("StockLocation")
                        .HasForeignKey("PTN.InventoryTracking.Domain.Entities.StockLocation", "VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_stock_locations_vehicles_vehicle_id");

                    b.HasOne("PTN.InventoryTracking.Domain.Entities.Warehouse", "Warehouse")
                        .WithOne("StockLocation")
                        .HasForeignKey("PTN.InventoryTracking.Domain.Entities.StockLocation", "WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_stock_locations_warehouses_warehouse_id");

                    b.Navigation("Vehicle");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("PTN.InventoryTracking.Domain.Entities.VehicleTask", b =>
                {
                    b.HasOne("PTN.InventoryTracking.Domain.Entities.InventoryTask", "Task")
                        .WithMany("VehicleTasks")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vehicle_tasks_tasks_task_id");

                    b.HasOne("PTN.InventoryTracking.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("VehicleTasks")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vehicle_tasks_vehicles_vehicle_id");

                    b.Navigation("Task");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("PTN.InventoryTracking.Domain.Entities.InventoryTask", b =>
                {
                    b.Navigation("InventoryTransactions");

                    b.Navigation("VehicleTasks");
                });

            modelBuilder.Entity("PTN.InventoryTracking.Domain.Entities.Product", b =>
                {
                    b.Navigation("InventoryTransactions");

                    b.Navigation("StockBalances");
                });

            modelBuilder.Entity("PTN.InventoryTracking.Domain.Entities.StockLocation", b =>
                {
                    b.Navigation("DestinationTransactions");

                    b.Navigation("SourceTransactions");

                    b.Navigation("StockBalances");
                });

            modelBuilder.Entity("PTN.InventoryTracking.Domain.Entities.Vehicle", b =>
                {
                    b.Navigation("StockLocation");

                    b.Navigation("VehicleTasks");
                });

            modelBuilder.Entity("PTN.InventoryTracking.Domain.Entities.Warehouse", b =>
                {
                    b.Navigation("StockLocation");
                });
#pragma warning restore 612, 618
        }
    }
}
